default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password:
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: reputasks_development
  
test:
  <<: *default
  database: reputasks_test

production:
  <<: *default
  database: reputasks_production
  username: reputasks
  password: <%= ENV['REPUTASKS_DATABASE_PASSWORD'] %>
